/**
 * Comprehensive Mock Data Store for Star e-Office.
 * Supplies realistic, rich Indonesian workspace data whenever Convex backend is disconnected.
 */

export const MOCK_ORGANIZATION = {
  _id: "org_star_01",
  _creationTime: Date.now() - 86400000 * 365,
  name: "PT Star Nusantara Digital",
  slug: "pt-star-nusantara",
  plan: "pro",
  isActive: true,
  isSampleOrg: true,
  createdAt: "2024-01-01T08:00:00.000Z",
  address: "Gedung Star Tower Lt. 12-15, Jl. Jend. Sudirman No. 45, Jakarta Selatan 12930",
  phone: "(021) 555-0199",
  website: "https://stareoffice.id",
  logoUrl: "https://hercules-cdn.com/file_TYr2Df58nZYpID6x8p76IO6J",
  industry: "Teknologi Informasi & Layanan Digital",
  employeeCount: 128,
};

export const MOCK_CURRENT_USER = {
  _id: "usr_cip_01",
  _creationTime: Date.now() - 86400000 * 180,
  name: "CIP 2017",
  email: "cipkai2017@gmail.com",
  role: "super_admin",
  jobTitle: "",
  department: "SDM DAN UMUM",
  accountStatus: "active",
  organizationId: "org_star_01",
  avatarUrl: "",
  phone: "+628128052324",
  isTestAccount: false,
  employeeId: "",
  nip: "",
  location: "",
  startDate: "2024-03-05",
  joinDate: "2024-03-05",
  address: "Pensiun BUMN",
  gender: "",
  birthDate: "",
  maritalStatus: "",
  managerName: "",
};

export const MOCK_USERS = [
  MOCK_CURRENT_USER,
  {
    _id: "usr_siti_02",
    _creationTime: Date.now() - 86400000 * 150,
    name: "Siti Nurhaliza, S.E.",
    email: "siti.haliza@stareoffice.id",
    role: "finance_manager",
    jobTitle: "Finance & Accounting Manager",
    department: "Keuangan",
    accountStatus: "active",
    organizationId: "org_star_01",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    phone: "0813-9876-5432",
    employeeId: "EMP-2024-002",
    joinDate: "2022-06-01",
  },
  {
    _id: "usr_budi_03",
    _creationTime: Date.now() - 86400000 * 120,
    name: "Budi Santoso",
    email: "budi.santoso@stareoffice.id",
    role: "employee",
    jobTitle: "Senior Software Engineer",
    department: "Teknologi Informasi",
    accountStatus: "active",
    organizationId: "org_star_01",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    phone: "0815-1122-3344",
    employeeId: "EMP-2024-003",
    joinDate: "2023-01-10",
  },
  {
    _id: "usr_dewi_04",
    _creationTime: Date.now() - 86400000 * 90,
    name: "Dewi Lestari, S.S.",
    email: "dewi.lestari@stareoffice.id",
    role: "employee",
    jobTitle: "Sekretaris Direksi",
    department: "Umum & Sekretariat",
    accountStatus: "active",
    organizationId: "org_star_01",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    phone: "0817-5566-7788",
    employeeId: "EMP-2024-004",
    joinDate: "2023-03-01",
  },
  {
    _id: "usr_rudi_05",
    _creationTime: Date.now() - 86400000 * 60,
    name: "Rudi Hartono, S.T.",
    email: "rudi.hartono@stareoffice.id",
    role: "manager",
    jobTitle: "Operations Manager",
    department: "Operasional",
    accountStatus: "active",
    organizationId: "org_star_01",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    phone: "0819-3344-5566",
    employeeId: "EMP-2024-005",
    joinDate: "2023-05-15",
  },
];

export const MOCK_DEPARTMENTS = [
  { _id: "dept_sdm", name: "SDM & Admin", code: "HRD", managerName: "Andi Wijaya", employeeCount: 12 },
  { _id: "dept_keuangan", name: "Keuangan & Akuntansi", code: "FIN", managerName: "Siti Nurhaliza", employeeCount: 18 },
  { _id: "dept_ti", name: "Teknologi Informasi", code: "ITD", managerName: "Budi Santoso", employeeCount: 42 },
  { _id: "dept_operasional", name: "Operasional", code: "OPS", managerName: "Rudi Hartono", employeeCount: 35 },
  { _id: "dept_pemasaran", name: "Pemasaran & Bisnis", code: "MKT", managerName: "Maya Indah", employeeCount: 21 },
];

export const MOCK_LETTERS = [
  {
    _id: "ltr_001",
    _creationTime: Date.now() - 86400000 * 2,
    letterNumber: "001/ND/HRD/VIII/2026",
    title: "Nota Dinas: Pelaksanaan Townhall Meeting Kuartal III",
    category: "Nota Dinas",
    type: "internal",
    senderName: "Andi Wijaya (Head of HR)",
    recipientName: "Seluruh Kepala Departemen",
    status: "disapproved_or_pending",
    approvalStatus: "pending",
    date: "2026-08-07",
    content: "Diberitahukan kepada seluruh Kepala Departemen bahwa Townhall Meeting Kuartal III akan dilaksanakan pada hari Jumat, 14 Agustus 2026.",
    isUrgent: true,
  },
  {
    _id: "ltr_002",
    _creationTime: Date.now() - 86400000 * 5,
    letterNumber: "042/SK/DIR/VIII/2026",
    title: "Surat Keputusan: Penetapan Tim Pelaksana ISO 27001",
    category: "Surat Keputusan",
    type: "internal",
    senderName: "Direksi",
    recipientName: "Tim ISO 27001",
    status: "signed",
    approvalStatus: "approved",
    date: "2026-08-04",
    content: "Menimbang perlunya peningkatan standar keamanan informasi perusahaan, maka dibentuk Tim ISO 27001.",
    isUrgent: false,
  },
  {
    _id: "ltr_003",
    _creationTime: Date.now() - 86400000 * 1,
    letterNumber: "105/UND/MKT/VIII/2026",
    title: "Undangan Kerjasama Kemitraan Digital Enterprise",
    category: "Surat Masuk",
    type: "incoming",
    senderName: "PT Mitra Digital Indonesia",
    recipientName: "Direktur Utama",
    status: "dispatched",
    approvalStatus: "approved",
    date: "2026-08-08",
    content: "Kami bermaksud mengundang pimpinan PT Star Nusantara Digital dalam pertemuan pembahasan kemitraan strategis.",
    isUrgent: true,
  },
];

export const MOCK_ATTENDANCE_TODAY = {
  _id: "att_today_01",
  userId: "usr_andi_01",
  date: new Date().toISOString().split("T")[0],
  status: "present",
  checkIn: "08:14:22",
  checkOut: null,
  workLocation: "WFO - Star Tower",
  notes: "Tepat waktu",
  lat: -6.2088,
  lng: 106.8456,
};

export const MOCK_LEAVE_REQUESTS = [
  {
    _id: "leave_001",
    _creationTime: Date.now() - 86400000 * 3,
    employeeName: "Andi Wijaya",
    leaveType: "Cuti Tahunan",
    startDate: "2026-08-20",
    endDate: "2026-08-22",
    totalDays: 3,
    reason: "Acara Keluarga di Bandung",
    status: "approved",
    approverName: "Direksi",
  },
  {
    _id: "leave_002",
    _creationTime: Date.now() - 86400000 * 1,
    employeeName: "Budi Santoso",
    leaveType: "Cuti Sakit",
    startDate: "2026-08-09",
    endDate: "2026-08-10",
    totalDays: 2,
    reason: "Demam dan Flu (Surat Dokter Terlampir)",
    status: "pending",
    approverName: "Andi Wijaya",
  },
];

export const MOCK_EXPENSES = [
  {
    _id: "exp_001",
    _creationTime: Date.now() - 86400000 * 4,
    title: "Pembelian Server Rack & Kabel LAN Cat6",
    category: "Peralatan IT",
    amount: 4750000,
    requestDate: "2026-08-05",
    status: "approved",
    requesterName: "Budi Santoso",
  },
  {
    _id: "exp_002",
    _creationTime: Date.now() - 86400000 * 2,
    title: "Reimbursement Jamuan Klien PT Bank Nusantara",
    category: "Entertainment & Klien",
    amount: 1250000,
    requestDate: "2026-08-07",
    status: "pending",
    requesterName: "Rudi Hartono",
  },
];

export const MOCK_FUND_REQUESTS = [
  {
    _id: "fund_001",
    title: "Pengajuan Dana Anggaran Pelatihan Cyber Security 2026",
    department: "Teknologi Informasi",
    amount: 18500000,
    requestDate: "2026-08-02",
    status: "approved",
    description: "Biaya sertifikasi Certified Ethical Hacker untuk 3 staf tim IT Security.",
  },
  {
    _id: "fund_002",
    title: "Pengajuan Dana Operasional Sewa Bus Gathering Perusahaan",
    department: "SDM & Admin",
    amount: 12000000,
    requestDate: "2026-08-08",
    status: "pending",
    description: "Sewa 2 unit bus pariwisata untuk acara tahunan di Puncak, Bogor.",
  },
];

export const MOCK_NEWS = [
  {
    _id: "news_001",
    _creationTime: Date.now() - 86400000 * 1,
    title: "Pengumuman: Penyesuaian Jam Kerja Bulan Agustus 2026",
    summary: "Manajemen mengumumkan penyesuaian fleksibilitas jam kerja hybrid (WFH/WFO) efektif minggu depan.",
    content: "Yth. Seluruh Karyawan PT Star Nusantara Digital,\n\nDalam rangka meningkatkan keseimbangan kerja dan kehidupan (work-life balance) serta efisiensi operasional, manajemen menetapkan kebijakan Hybrid Working 3 WFO / 2 WFH per minggu mulai tanggal 15 Agustus 2026.\n\nDemikian pengumuman ini disampaikan untuk dilaksanakan.",
    publishedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    authorName: "Tim HR & Komunikasi",
    category: "Pengumuman Resmi",
    coverUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&auto=format&fit=crop&q=80",
  },
  {
    _id: "news_002",
    _creationTime: Date.now() - 86400000 * 4,
    title: "Peluncuran Fitur Baru Star e-Office v2.5: Modul Keuangan & Tanda Tangan Digital",
    summary: "Update terbaru aplikasi Star e-Office menghadirkan integrasi modul keuangan, pencatatan otomatis audit trail, dan QR Code verifikasi dokumen.",
    content: "Sistem Star e-Office versi 2.5 telah resmi meluncur! Nikmati pengalaman kelola arsip, verifikasi surat dinas berbasis QR Code, dan absensi terintegrasi lokasi GPS.",
    publishedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    authorName: "Tim Pengembang e-Office",
    category: "Pembaruan Sistem",
    coverUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=600&auto=format&fit=crop&q=80",
  },
];

export const MOCK_PROJECTS = [
  {
    _id: "proj_001",
    name: "Digitalisasi Arsip Kantor & E-Sign",
    code: "PRJ-2026-01",
    status: "in_progress",
    progress: 78,
    dueDate: "2026-09-30",
    leadName: "Budi Santoso",
    membersCount: 8,
    description: "Proyek pemindaian, pengindeksan, dan migrasi seluruh dokumen fisik kantor ke sistem Star e-Office.",
  },
  {
    _id: "proj_002",
    name: "Sertifikasi ISO 27001 Keamanan Informasi",
    code: "PRJ-2026-02",
    status: "in_progress",
    progress: 45,
    dueDate: "2026-11-15",
    leadName: "Andi Wijaya",
    membersCount: 12,
    description: "Penyusunan Kebijakan Keamanan, Manajemen Risiko IT, dan Audit Kepatuhan ISO/IEC 27001:2022.",
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    _id: "notif_001",
    _creationTime: Date.now() - 3600000 * 2,
    title: "Surat Masuk Baru Perlu Disposisi",
    message: "Surat UND/MKT/VIII/2026 dari PT Mitra Digital memerlukan tindakan disposisi Anda.",
    isRead: false,
    link: "/letters",
    type: "letter",
  },
  {
    _id: "notif_002",
    _creationTime: Date.now() - 3600000 * 5,
    title: "Pengajuan Cuti Disetujui",
    message: "Pengajuan Cuti Tahunan tanggal 20-22 Agustus 2026 telah disetujui oleh Direksi.",
    isRead: true,
    link: "/leave",
    type: "leave",
  },
  {
    _id: "notif_003",
    _creationTime: Date.now() - 3600000 * 24,
    title: "Pengingat Absensi Masuk",
    message: "Jangan lupa untuk melakukan Check-In absensi pagi ini sebelum pukul 08:30 WIB.",
    isRead: true,
    link: "/attendance",
    type: "attendance",
  },
];

export const MOCK_EVENTS = [
  {
    _id: "evt_001",
    title: "Rapat Koordinasi Evaluasi Kuartal III",
    startDate: "2026-08-14T09:00:00",
    endDate: "2026-08-14T11:30:00",
    location: "Ruang Meeting Utama - Lt. 12 & Zoom",
    organizer: "Andi Wijaya",
    attendeesCount: 24,
  },
  {
    _id: "evt_002",
    title: "Workshop Security Awareness & Phishing Simulation",
    startDate: "2026-08-18T13:30:00",
    endDate: "2026-08-18T16:00:00",
    location: "Auditorium Star e-Office",
    organizer: "Tim IT Security",
    attendeesCount: 85,
  },
];

export const MOCK_DOCUMENTS = [
  {
    _id: "doc_001",
    title: "Pedoman Tata Kelola Persuratan & Arsip Digital (SOP-01/HR/2026)",
    category: "SOP & Kebijakan",
    fileSize: "2.4 MB",
    updatedAt: "2026-07-15",
    authorName: "Tim Legal & HR",
  },
  {
    _id: "doc_002",
    title: "Template Resmi Kop Surat & Nota Dinas Perusahaan",
    category: "Template",
    fileSize: "850 KB",
    updatedAt: "2026-08-01",
    authorName: "Sekretariat Corporate",
  },
];

export const MOCK_SITE_VISIBILITY = {
  hero: true,
  stats: true,
  trustedBy: true,
  features: true,
  demo: true,
  benefits: true,
  modules: true,
  workflow: true,
  calls: true,
  security: true,
  testimonial: true,
  pricing: true,
  cta: true,
  footer: true,
};
